name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Setup XMLLint bc otherwise break
        run: sudo apt-get install libxml2-utils -y
      - run: npm install --no-frozen-lockfile
      - run: npm run ci
